name: titanic-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.1
  - seaborn=0.13.2
  - scikit-learn=1.7.0
  - xgboost=3.0.2
  - psutil=7.0
  - pip
  - pytest==8.4.1
  - pip:
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - dvc[s3]==3.61.0
      - httpx==0.28.1
      - prometheus_client==0.22.1