global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'titanic-api'
    metrics_path: /prometheus
    static_configs:
      - targets: ['titanic-api:8000']
        labels:
          group: 'api'
