{
 "title": "API Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Average Request Latency (seconds, 5m rate)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(api_request_latency_seconds_sum[5m]) / rate(api_request_latency_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API CPU Usage (%)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "API Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 32, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "API Requests Total",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "api_requests_total",
     "legendFormat": "{{method}} {{endpoint}} {{http_status}}"
    }
   ]
  }
 ]
}